### ISSUE TITLE
Down alert every 3 hours

### ISSUE THREAD

**Issue by JbIPS** [lexoyo/Monitoshi#3]
Hi, 

I'm using Monitoshi to monitor a Node.JS server run with `pm2`.

Every 3h, (0h05, 3h05, 6h05, 9h05,...) Monitoshi sends me a mail that the service is down. It looked suspicious (due to the regularity) so I looked at the Keymetrics dashboard: no error and service up for a week.

So now I'm suspecting some false positive on Monitoshi. Any leads?

**Comment by lexoyo** [comment]
Fixed
